common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $verification_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_INACTIVE = 9;
    const STATUS_ACTIVE = 10;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_INACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds user by verification email token
     *
     * @param string $token verify email token
     * @return static|null
     */
    public static function findByVerificationToken($token) {
        return static::findOne([
            'verification_token' => $token,
            'status' => self::STATUS_INACTIVE
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Generates new token for email verification
     */
    public function generateEmailVerificationToken()
    {
        $this->verification_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

common/models/Users.php
<?php

namespace common\models;

use Yii;
use yii\web\IdentityInterface; 

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $email Correo electrónico
 * @property string $password Contraseña
 * @property string $name Nombre
 * @property string $surname Apellidos
 * @property string|null $phone Teléfono
 * @property int|null $active Activo
 * @property int|null $approved Aprovador por un administrador
 * @property int $id_company Empresa
 * @property int $id_user_type
 * @property int|null $id_referred
 * @property int|null $id_agency
 */
class Users extends \yii\db\ActiveRecord implements IdentityInterface
{
    const ADMIN = 1;
    const PROVIDER = 2;
    const CUSTOMER = 3;
    const REFERRED = 4;
    const AGENCY = 5;
    const AFFILIATE = 6;
    const CONTEST   = 7;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['email', 'name', 'surname', 'id_company', 'id_user_type'], 'required'],
            [['active', 'approved', 'id_company', 'id_user_type', 'id_referred', 'id_agency'], 'integer'],
            [['email', 'name', 'surname', 'phone'], 'string', 'max' => 180],
            [['password'], 'string', 'max' => 240],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email' => 'Email',
            'password' => 'Password',
            'name' => 'Name',
            'surname' => 'Surname',
            'phone' => 'Phone',
            'active' => 'Active',
            'approved' => 'Approved',
            'id_company' => 'Id Company',
            'id_user_type' => 'Id User Type',
            'id_referred' => 'Id Referred',
            'id_agency' => 'Id Agency',
        ];
    }

   

    /**
    * @return \yii\db\ActiveQuery
    */
    public function getComments()
    {
        return $this->hasMany(Comments::className(), ['id_user_approved' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTours()
    {
        return $this->hasMany(Tour::className(), ['id_user_created' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTours0()
    {
        return $this->hasMany(Tour::className(), ['last_user_updated' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(Company::className(), ['id' => 'id_company']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(UsersType::className(), ['id' => 'id_user_type']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReferred()
    {
        return $this->hasOne(Referred::className(), ['id' => 'id_referred']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgency()
    {
        return $this->hasOne(Agency::className(), ['id' => 'id_agency']);
    }
    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIsAdmin()
    {
        return $this->id_user_type === self::ADMIN;
    }

    public function getIsProvider(){
        return $this->id_user_type === self::PROVIDER;
    }
    
    public function getIsReferred(){
        return $this->id_user_type === self::REFERRED;
    }
    
    public function getIsAgency(){
        return $this->id_user_type === self::AGENCY;
    }

    public function getIsAffiliate(){
        return $this->id_user_type === self::AFFILIATE;
    }

    public function getIsContest(){
        return $this->id_user_type === self::CONTEST;
    }

    /**
     * {@inheritdoc}
     * @return UsersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UsersQuery(get_called_class());
    }

    /** 
    * Finds an identity by the given ID. 
    * 
    * @param string|int $id the ID to be looked for 
    * @return IdentityInterface|null the identity object that matches the given ID. 
    */ 
    public static function findIdentity($id) 
    { 
       return static::findOne($id); 
    } 
 
    /** 
    * Finds an identity by the given token. 
    * 
    * @param string $token the token to be looked for 
    * @return IdentityInterface|null the identity object that matches the given token. 
    */ 
   public static function findIdentityByAccessToken($token, $type = null) 
   { 
       return static::findOne(['access_token' => $token]); 
   } 
   /** 
    * Finds an identity by the given token. 
    * 
    * @param string $token the token to be looked for 
    * @return IdentityInterface|null the identity object that matches the given token. 
    */ 
   public static function findEmail($email, $type = null) 
   { 
       return static::findOne(['email' => $email]); 
   } 
 
   /** 
    * @return int|string current user ID 
    */ 
   public function getId() 
   { 
       return $this->id; 
   } 
   
   /** 
    * @return int|string current user ID 
    */ 
    public function getUsername() 
    { 
        return $this->email; 
    } 

   /** 
    * @return string current user auth key 
    */ 
   public function getAuthKey() 
   { 
       return $this->password; 
   } 
 
   /** 
    * @param string $authKey 
    * @return bool if auth key is valid for current user 
    */ 
   public function validateAuthKey($authKey) 
   { 
       return $this->getAuthKey() === $authKey; 
   } 
 
//    public function beforeSave($insert) 
//    { 
//        if (parent::beforeSave($insert)) { 
//            if ($this->isNewRecord) { 
//                $this->auth_key = \Yii::$app->security->generateRandomString(); 
//            } 
//            return true; 
//        } 
//        return false; 
//    } 
 
 
   /** 
    * Validates password 
    * 
    * @param string $password password to validate 
    * @return bool if password provided is valid for current user 
    */ 
   public function validatePassword($password) 
   { 
       $hash = Yii::$app->security->generatePasswordHash($password);
       return Yii::$app->getSecurity()->validatePassword($password, $hash);
   } 


   /**
     * @return boolean
     */
    public function canUpdateRecord()
    {
        if (Yii::$app->user->identity->isAdmin) {
            // Perform custom validation here regardless of "name" attribute value and add error when needed
            if (!Yii::$app->user->identity->isAdmin && isset($this->attributes)) {
                if ($this->attributes["id_user_type"] != 6) {

                if(Yii::$app->user->identity->id_company != $this->attributes["id_company"]){

                        Yii::$app->session->setFlash('error', "La empresa seleccionada no existe");
                        $this->addError('id_company', 'La empresa seleccionada no existe');
                    }
                }

                
            }
        }
    }
 
}

common/models/UsersType.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "users_type".
 *
 * @property int $id
 * @property string $name
 */
class UsersType extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users_type';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * {@inheritdoc}
     * @return UsersTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UsersTypeQuery(get_called_class());
    }
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Users;
use common\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends AdminController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = 'mainv2';
        $model = new Users();
      

        if ($model->load(Yii::$app->request->post())) {
            $model->password = password_hash($model->password, PASSWORD_DEFAULT);
            $model->active = ($model->active !== '') ?  $model->active : 0;
            $model->approved = ($model->approved !== '') ?  $model->approved : 0;

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }


        $this->registerJsFiles([
            [
                'url' => '@web/javascript/v2/user.create.js',
                'position' => \yii\web\View::POS_END,
                'depends' => [\yii\web\JqueryAsset::className()]
            ],
        ]);

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/users/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
    <? if($updateForm ) : ?>
        <p class="help-block">Deja en blanco la contraseña para no cambiarla.</p>
    <? endif; ?>
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'active')->dropDownList([1=>'Si', 0=>'No'], ['prompt'=>'Seleccione uno']  );?>

    <?= $form->field($model, 'approved')->dropDownList([1=>'Si', 0=>'No'], ['prompt'=>'Seleccione uno']  );?>

    <? if(Yii::$app->user->identity->isAdmin) :?>
        <?= $form->field($model, 'id_user_type')->dropDownList(
            ArrayHelper::map(common\models\UsersType::find()->asArray()->all(), 'id', 'name'),
            ['prompt'=>'Seleccione uno']  );
        ?>

        <div id="section-company" style="display:none;">
            <?= $form->field($model, 'id_company')->dropDownList(
                ArrayHelper::map(common\models\Company::find()->asArray()->all(), 'id', 'name'),
                ['prompt'=>'Seleccione uno']  );
            ?>
        </div>
        
    <? else :?>
    <?= $form->field($model, 'id_company')->hiddenInput(['value'=> $model->id_company])->label(false);?>
    <? endif; ?>


   

    <div class="form-group" >
        <?= Html::submitButton(Yii::t('app', 'Guardar'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\UsersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'surname') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'active') ?>

    <?php // echo $form->field($model, 'approved') ?>

    <?php // echo $form->field($model, 'id_company') ?>

    <?php // echo $form->field($model, 'id_user_type') ?>

    <?php // echo $form->field($model, 'id_referred') ?>

    <?php // echo $form->field($model, 'id_agency') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/users/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Users */

$this->title = 'Create Users';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/users/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\ArrayHelper;
use common\models\Users;
/* @var $this yii\web\View */
/* @var $searchModel common\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Todos los usuarios');
$this->params['breadcrumbs'][] = $this->title;
?>

<?php $this->beginBlock('page-header'); ?>
<?= Html::encode($this->title) ?>
<?php $this->endBlock(); ?>

<div class="users-index">

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Agregar usuario'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'pager' => [
            'options'=> [
                'class' => 'pagination pagination-lg',
            ]
        ],
        'rowOptions' => function ($model) {
            switch ($model['active']) {
                case 0 : return ['class' => 'warning'];
                case 1: return ['class' => ''];
                default: return [];
            }
        },
        'columns' => [
            'name',
            'surname',
            //'phone',
            [
                'attribute'=>'active',
                'filter'=>[
                    ''=>'Todos',
                    1=>'Si',
                    0=>'No'
                ],
                'value'=> function ($model) {
                    return $model->active == 1 ? 'Si' : 'No';
               },
                'label' => 'Activado',
            ],
            [
                'attribute'=>'approved',
                'filter'=>[
                    ''=>'Todos',
                    1=>'Si',
                    0=>'No'
                ],
                'value'=> function ($model) {
                    return $model->approved == 1 ? 'Si' : 'No';
               },
                'label' => 'Aprobado',
            ],
            [
                'attribute'=>'id_company',
                'filter'=> ArrayHelper::map(common\models\Company::find()->orderBy(['name' => SORT_ASC,])->all(),'id','name'),
                'label' => 'Empresa',
                'value'=> function ($model){
                    if($model->id_user_type == Users::ADMIN) {
                        return 'Administrador';    
                    } else {
                        return $model->company->name;
                    }
                    
                },
                'visible' => ($_GET['UsersSearch']['id_user_type'] != Users::AGENCY)
            ],
            [
                'attribute'=>'id_user_type',
                'filter'=> ArrayHelper::map(common\models\UsersType::find()->orderBy(['name' => SORT_ASC,])->all(),'id','name'),
                'label' => 'Tipo de usuario',
                'value'=> 'type.name',
                'visible' => Yii::$app->user->identity->isAdmin
            ],
            'email:email',
        
           // 'id_company',

            [
                'class' => 'yii\grid\ActionColumn',
                'template'=>'{view} {update} {delete}',
                'buttons'=>[
                    'delete' => function ($url, $model) {  
                        $url = Url::to(['users/delete', 'id' => $model->id]);   
                        return  Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                            'title'        => 'delete',
                            'data-confirm' => Yii::t('yii', '¿Esta seguro que desea desactivar a este usuario?'),
                            'data-method'  => 'post',
                        ]);                           
                    }
                ]        
            ],
        ],
    ]); ?>


    <?php Pjax::end(); ?>
</div>

backend/views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Users */

$this->title = 'Update Users: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="users-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Users */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="users-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'email:email',
            'password',
            'name',
            'surname',
            'phone',
            'active',
            'approved',
            'id_company',
            'id_user_type',
            'id_referred',
            'id_agency',
        ],
    ]) ?>

</div>